version: '3.7'

volumes:
  postgres_data:
  static_data:
  # frontend_data:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: djangoproject/Dockerfile
      cache_from:
        - subangkar/mememaker:initial
    image: subangkar/mememaker:initial
    volumes:
      - static_data:/vol/web
    ports:
      - 8000:8000 # change also in uwsig ini  and ngnix conf upstream
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db


  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/prod/Dockerfile
  #   ports:
  #     - 80:80 # change in ngnix conf
  #   volumes:
  #     - static_data:/vol/static
  #     # - frontend_data:/vol/frontend/static
  #   # env_file:
  #   #   - nginx/prod/.env.dev
  #   depends_on:
  #     - web

  # vue:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   env_file:
  #     - frontend/.env.dev
  #   volumes:
  #     - frontend_data:/app
  #   depends_on:
  #     - web
  #     - nginx
